-- Add all missing permissions for comprehensive role-based access control
-- Admin permissions (all should be true)
INSERT INTO public.role_permissions (role, permission, allowed) VALUES 
  ('admin', 'create_articles', true),
  ('admin', 'edit_own_articles', true),
  ('admin', 'delete_own_articles', true),
  ('admin', 'manage_videos', true),
  ('admin', 'manage_bonuses', true),
  ('admin', 'moderate_comments', true),
  ('admin', 'manage_content_flags', true),
  ('admin', 'manage_giveaways', true),
  ('admin', 'manage_events', true),
  ('admin', 'manage_gtw', true),
  ('admin', 'manage_polls', true),
  ('admin', 'manage_bonus_hunt', true),
  ('admin', 'send_notifications', true),
  ('admin', 'change_live_status', true),
  ('admin', 'manage_streamers', true),
  ('admin', 'manage_users', true),
  ('admin', 'view_user_details', true),
  ('admin', 'manage_settings', true),
  ('admin', 'manage_branding', true),
  ('admin', 'manage_legal_pages', true),
  ('admin', 'manage_webhooks', true),
  ('admin', 'bulk_actions', true),
  ('admin', 'view_audit_logs', true),
  ('admin', 'view_own_analytics', true),
  ('admin', 'view_dev_diagnostics', true),
  ('admin', 'bypass_maintenance', true)
ON CONFLICT DO NOTHING;

-- Moderator permissions
INSERT INTO public.role_permissions (role, permission, allowed) VALUES 
  ('moderator', 'create_articles', true),
  ('moderator', 'edit_own_articles', true),
  ('moderator', 'delete_own_articles', true),
  ('moderator', 'manage_videos', true),
  ('moderator', 'manage_bonuses', true),
  ('moderator', 'moderate_comments', true),
  ('moderator', 'manage_content_flags', true),
  ('moderator', 'manage_giveaways', true),
  ('moderator', 'manage_events', true),
  ('moderator', 'manage_gtw', true),
  ('moderator', 'manage_polls', true),
  ('moderator', 'manage_bonus_hunt', true),
  ('moderator', 'send_notifications', false),
  ('moderator', 'change_live_status', true),
  ('moderator', 'manage_streamers', true),
  ('moderator', 'manage_users', false),
  ('moderator', 'view_user_details', true),
  ('moderator', 'manage_settings', false),
  ('moderator', 'manage_branding', false),
  ('moderator', 'manage_legal_pages', false),
  ('moderator', 'manage_webhooks', false),
  ('moderator', 'bulk_actions', false),
  ('moderator', 'view_audit_logs', false),
  ('moderator', 'view_own_analytics', true),
  ('moderator', 'view_dev_diagnostics', false),
  ('moderator', 'bypass_maintenance', true)
ON CONFLICT DO NOTHING;

-- Writer permissions
INSERT INTO public.role_permissions (role, permission, allowed) VALUES 
  ('writer', 'create_articles', true),
  ('writer', 'edit_own_articles', true),
  ('writer', 'delete_own_articles', false),
  ('writer', 'manage_videos', false),
  ('writer', 'manage_bonuses', false),
  ('writer', 'moderate_comments', false),
  ('writer', 'manage_content_flags', false),
  ('writer', 'manage_giveaways', false),
  ('writer', 'manage_events', false),
  ('writer', 'manage_gtw', false),
  ('writer', 'manage_polls', false),
  ('writer', 'manage_bonus_hunt', false),
  ('writer', 'send_notifications', false),
  ('writer', 'change_live_status', false),
  ('writer', 'manage_streamers', false),
  ('writer', 'manage_users', false),
  ('writer', 'view_user_details', false),
  ('writer', 'manage_settings', false),
  ('writer', 'manage_branding', false),
  ('writer', 'manage_legal_pages', false),
  ('writer', 'manage_webhooks', false),
  ('writer', 'bulk_actions', false),
  ('writer', 'view_audit_logs', false),
  ('writer', 'view_own_analytics', true),
  ('writer', 'view_dev_diagnostics', false),
  ('writer', 'bypass_maintenance', false)
ON CONFLICT DO NOTHING;

-- User permissions (mostly disabled)
INSERT INTO public.role_permissions (role, permission, allowed) VALUES 
  ('user', 'create_articles', false),
  ('user', 'edit_own_articles', false),
  ('user', 'delete_own_articles', false),
  ('user', 'manage_videos', false),
  ('user', 'manage_bonuses', false),
  ('user', 'moderate_comments', false),
  ('user', 'manage_content_flags', false),
  ('user', 'manage_giveaways', false),
  ('user', 'manage_events', false),
  ('user', 'manage_gtw', false),
  ('user', 'manage_polls', false),
  ('user', 'manage_bonus_hunt', false),
  ('user', 'send_notifications', false),
  ('user', 'change_live_status', false),
  ('user', 'manage_streamers', false),
  ('user', 'manage_users', false),
  ('user', 'view_user_details', false),
  ('user', 'manage_settings', false),
  ('user', 'manage_branding', false),
  ('user', 'manage_legal_pages', false),
  ('user', 'manage_webhooks', false),
  ('user', 'bulk_actions', false),
  ('user', 'view_audit_logs', false),
  ('user', 'view_own_analytics', false),
  ('user', 'view_dev_diagnostics', false),
  ('user', 'bypass_maintenance', false)
ON CONFLICT DO NOTHING;